// =====================================================
// כל תוכן האתר הניתן לעריכה — ערוך דרך admin.html
// =====================================================

window.SITE_DATA = {

  // ── סרטון ──────────────────────────────────────────
  // הדבק כאן רק את ה-ID מיוטיוב (הספרות אחרי ?v= או youtu.be/)
  // דוגמה: https://www.youtube.com/watch?v=dQw4w9WgXcQ  →  youtubeId: "dQw4w9WgXcQ"
  video: {
    youtubeId: "",
    facebookUrl: ""
  },

  // ── גלריה ──────────────────────────────────────────
  // cat: events | workshops | characters | hats
  gallery: [
    // ── עיצוב אירועים ──
    { src: "https://lh3.googleusercontent.com/d/17Y2wTaAQDy6B_9I_2BIkfSDvF4oh_XT8", cat: "events",     alt: "עיצוב אירוע בלונים" },
    { src: "https://lh3.googleusercontent.com/d/19UqXV7TgDie9DsAibfCqia-PhnGWg7ur", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1yoJ44JB1c4X_wpyBg0bCUixMie_yS8uD", cat: "events",     alt: "עיצוב אירוע בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1mGC5W7uObOS0icYKgV7Kb2yaTt7FSoEF", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/13fbxvQ3P4hmyiANvDOb92bY6smQtmBiH", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1YGTTI109X0JD8i0ppwWjXSWa4I7I0KZM", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1N1SDBNSOUBkEt0sQkRUh4r-WKn5BjWw7", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/11RwiYLIooZGFQlWigc8wXFSd6N-ruiuD", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1y9my-rOhDUhRVeONR1zNKd_nxH7XDazY", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1Kk-_o15MxTKNly5eIdkPIkEo-7-9bW3e", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/10U2hJ2jIDYWKc3KO1vXAl5QVIKrQqzDI", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/12QshG_RC_GajTmVh2ZT0lUZu6JUR1n7X", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/10xfXy7juZNWimdvjh7X6JVkWFd995ww8", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1DRKWjztjqr7c2RQxCAP0LJGkSNcLghvp", cat: "events",     alt: "עיצוב אירוע בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1FTrwcf0Dx9VgfMx4EeqY5HuuLxIpEmdo", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1wBHOyYzXSxtjNXVZox0ieoDwT7W3aA6-", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1McL_2I7sy57qTbbzHvznqZI8rOYGDykz", cat: "events",     alt: "עיצוב אירוע מקצועי" },
    { src: "https://lh3.googleusercontent.com/d/13z6KHNrtkDItJeYaXcZ4olUzdYgSnM-E", cat: "events",     alt: "עיצוב בלונים מקצועי" },
    { src: "https://lh3.googleusercontent.com/d/1LolCXm32Hyp-DRjJlvE6xgL6Adhdpuoa", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1VIcB0KlNOwMcVfF34T7J4-0PoMImSC2A", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1EluLClwYIdl87Fg6UddJBsA7piYfVEMI", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/10yoERQG7QeRFg1JlssqNt3sNp77K_tpk", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1BctzD8znF2AHAxN7C99_e-4HzYqQfu-g", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1H4ya89uM5Dw--QFr4EDGxlXocmyFjGlI", cat: "events",     alt: "עיצוב אירוע מקצועי" },
    { src: "https://lh3.googleusercontent.com/d/1sbDx1qB13Oyjpfswqlx6dGoCY_bvcuMq", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1IVdUC6TJRCehnJ9xCLFPKtLR9di9B0T2", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1OqJhvcHDTzLTA7LtLqYRFXC4Au53h2qG", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1AB7duGcHaJAiL021um2AHnjLkNumjAGu", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1ECuj2NoCYW9SuBsbc_40gT29Vj5zt9IQ", cat: "events",     alt: "עיצוב אירוע מקצועי" },
    { src: "https://lh3.googleusercontent.com/d/1DonqwKMJca_MzUlNh6E6lR9zz8Yl5CbB", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1z6ywEYSrOCCgiVfHoucUePId-U85yJ8v", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1-ifvTEfECVlJuE34KVFoRKysAqT1_XEH", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1gIa1-oqhR5gUh7fZTuBJzRzY_znOfR_q", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1a8fDNZuixAaid3RaiHgUz_cAcw6DJT3y", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/105hk5Q2808oh4yX4472uYWUami9P7UAv",  cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/12zJBOIqKSA86tZeW4JhayjzGEgW50IOU", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1pvMaCNz4tTHv1YQ3qErNn9WUV_Lz0F86", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1Z4HYJBHmLVx7q-hcqX6lj0RNqjMZkYTx", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1OPa75tUmgZNsxvk_ezzpuIBf6XV0tqTT", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1DdtYK0t6UFFY3j7TbLLl-rK4JpO1GK8n", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1QyZmdauSX0adCwja1k98XPl6hDtCZpij", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/16Ul0h7-_59R9I3ViyimC3TChmgtlsCx5", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1OvOGZrs4DKiPtsaiAptw7b-iCbS8C85H", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/10GTaI7YOB7B2lg-oNgJgz9Ep3gCXv5mE", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1aOxentuOkQT40oYsz0VA7B8fcaggpgEz", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1U86uUiMlJ1PfCJDepDQczklDYsHHfncp", cat: "events",     alt: "עיצוב אירוע" },
    { src: "https://lh3.googleusercontent.com/d/1l_SGm50l6exu1hWJYLTHSZnjWDAFvupY", cat: "events",     alt: "עיצוב בלונים" },
    { src: "https://lh3.googleusercontent.com/d/19NDodVR4gCbUSXR8mDIGCSl1ySFDv2RE", cat: "events",     alt: "בלונים לאירוע" },
    { src: "https://lh3.googleusercontent.com/d/1KVqY6r9UBZr0knDPeWSNwa0n4_ZEZEU9", cat: "events",     alt: "עיצוב אירוע" },
    // ── דמויות ובר בלונים ──
    { src: "https://lh3.googleusercontent.com/d/1PsEWzu4sjG4jJSbLhijK8XJI48kKczBf", cat: "characters", alt: "בר בלונים — דמויות" },
    { src: "https://lh3.googleusercontent.com/d/1EmGgb_GKr4lDqUKjIjPXLj1GRLkC9xF3", cat: "characters", alt: "בר בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1pnXx_uEd3dTVu7S5AhBO2yvUYqtQSaAx", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1fj6R07b3iDhJlMUWxWnG4UYiuH1NNV2f", cat: "characters", alt: "בר בלונים מקצועי" },
    { src: "https://lh3.googleusercontent.com/d/1nIVIf0M9qmCqDejaOuD60nftpxsXbjVc", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1bHOvmxVj2dTUVEv-Wykv2d3Ev3Sd2PDo", cat: "characters", alt: "בר בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1dhkAOVhpkEf09nXfzv_60NU7RXs3PVw-", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/15L9qLOKMS5FyhNpsRRl7efhVvKDyWk8X", cat: "characters", alt: "בר בלונים — עבודת אמן" },
    { src: "https://lh3.googleusercontent.com/d/1608Ha5Ug_wz0V9qqWV4G4Uk0bHAedVdw", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1pgOGe6ogDAXcl3tYbR1MEqkcpO1P42Kn", cat: "characters", alt: "דמות בלונים מיוחדת" },
    { src: "https://lh3.googleusercontent.com/d/159mA1L8BrH624yCBK1hC-BZCkndKBCQG", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1QQzfvCP0MHLowc4H5P-3Uvb2fKDAJApm", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1lS6fmu1l6UA_o4vEiGcs4L7EYznl5DEK", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1xJot5Hp85VrrTrj13XBd2dntqAO1aMFQ", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1P2D2QUOicyqTIAfmhdaYa43oTJqvVpSY", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1EAfBEXK3oG5TmkUgdE4mXL5__DB1F3zh", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1gq0z5pQKMsuwDLIRcLz3Ki7Zba0nr4oy", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1xO1EyHKKD5DG6F0oJ_yvrY4h7XGdSd6s", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1fn0oy5KPsYdIi00ebALr-IxViAi40YlZ", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1l-qdprJKdesoByWFS1OU9j6H359ubYZ7", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1HPdK1aHCAE1e2JE5Dom6hjAB-I6PKlTn", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1kNz7LCoFFj62V6P3S6dAyu7wsQm3irLj", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1JoHoDJf-JBHj9Uhg_zvwA8CRmKe5G9eg", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1wVUYjo5Pekrn_a9MrhJJX5B7B8pMk6yP", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1VXuvhOCcZabf2U81DB54csX2H04q1_cT", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1QZG3jvkbu4_BnbQQRFn6QiKPz-uWDyh7", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1XujwwOQTIroypcJF3KbQAj98gbUNtFmb", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1b1J05eQnNID3EVf-w3wjWmG0aCgJLKbG", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/14A5qPFvcdI-p_xtW5CR3di7ExOsJE7Pc", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1T1Y-A2GHX9Fw86E2frBuSKOc-Q9mQ9z2", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/19UCkKp3cBAYIf52C-32VH3qeUMo0NMqG", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1vwVkhHAyNDT846eORppUDKaIn_j8T9KJ", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/16gFDvxyrmdJulO3STiLjgt1KGGNQgj77", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1BzjnBJxcoq9sv1c6MS9lyDfcPcuIIzNH", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1wXx2ViWq3cXcoXNPrnrjDIB8G3b7Dzd7", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/19oi4KGUENKTd1Y69H_ylnvZ-gbvPWaSg", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1-nP8oVztf4RI2gaPk_47Yhu7ZzEXIE7B", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/19ardtLASYz30-52ulfIblETT1z-mu6RI", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1j1nl8WMlxwvZJh_zybaUjIQ-cu-TpEqN", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1FiUPieUsHwWD7HTItI7RKIAuFekygZoB", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1YcuP79nvama2Myc18Lny3AFNZvcPKagZ", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1rrTm_fYlG5OVwbhZMe-CcKFUMuGQUYlF", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/16tfBgLw6mj1q3E5QngYyIRIyAoXm7hxF", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/10lJoJ7sRDpA_jEWdqwFJYc_YZ-1yRIeP", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1PPO3PThpkQRNIMDvplscn_zw0njyDymk", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/11MqZIwOT-4abZjjpfudcYRG3AoxhHrKW", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1udg9P1afiecfBPSB2Wz8xWRj-fXuv1Jd", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1TUEGfJtA5ErVbQS6p9GmY6bn3gufToN2", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1LT0-iKB2Q9AvnP4ImfPFZOluoDXwpa9L", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1L7qKnkxHxK2jRwexlbnF7_N6lK1fUSbx", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1P-KQLBvWOinm844ZwnBWHkDAPAaBBBSF",  cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/1GCwf8tQ2O2TrzHe0_L70jMchMW3mVIhB", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/10C3ktI1FoTCCh82zAijdPUqp2sm0aMQf", cat: "characters", alt: "דמות מבלונים" },
    { src: "https://lh3.googleusercontent.com/d/16TcsnYYFHIs5w2fjrCUO8jkxtTZfvPt7", cat: "characters", alt: "דמות בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1i9WsRQmnHxYHhqq43XNaRVhQLg3FYgdm", cat: "characters", alt: "דמות מבלונים" },
    // ── סדנאות ──
    { src: "https://lh3.googleusercontent.com/d/1O0Yi6qyCV0v2tELncflb8VXqDCWWr1JN", cat: "workshops",  alt: "סדנת בלונים" },
    { src: "https://lh3.googleusercontent.com/d/10D1mbLPQ0mfiUmMY71ORExz8dtER1CMS", cat: "workshops",  alt: "סדנת יצירה" },
    { src: "https://lh3.googleusercontent.com/d/1qnjvzwaMuGc3ItMVsFybJpMkLXBgyd0s", cat: "workshops",  alt: "סדנת בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1g8e33xTPQMl2dkIQTvWsxdzM_N4MOf47", cat: "workshops",  alt: "סדנת יצירה" },
    { src: "https://lh3.googleusercontent.com/d/1-xgLlU9lgftGXwwFFb3kMIWQvkmaGGFd", cat: "workshops",  alt: "סדנת בלונים" },
    { src: "https://lh3.googleusercontent.com/d/1ns-bCOZya2KE1MhE9EsDmnEGVFqj1o2K", cat: "workshops",  alt: "סדנה" },
    { src: "https://lh3.googleusercontent.com/d/1tsMJTn_BkdMExAePChFvXMAxc4HhWib0", cat: "workshops",  alt: "סדנת בלונים" }
  ],

  // ── המלצות ─────────────────────────────────────────
  // photo:      תמונת פרופיל של הממליץ (אופציונלי — מגוגל דרייב)
  // screenshot: צילום מסך שיחת וואטסאפ (אופציונלי)
  testimonials: [
    { name: "חנה אור",             text: "הושעיה היה אצלנו בברית. הפך את האירוע להרבה יותר משמח ומיוחד. בעל גישה נהדרת לילדים. זורם וכמובן שמוכשר בעבודתו. ממליצה עליו בגדול!", photo: "", screenshot: "" },
    { name: "דוד לוין",             text: "מומלץ ביותר!! מקצוען ותותח", photo: "", screenshot: "" },
    { name: "אביאל כהן",           text: "הושעיה היקר היה פשוט מדהים!! איזה בלונים יפים זה פשוט העיף את החתונה באוויר!!! תודה תודה תודה", photo: "", screenshot: "" },
    { name: "אריה לייב שפירא",     text: "הושעיה היה מפעיל בלונים בחתונה שלנו, וזה היה מדהים. הגיע עם בלונים מוכנים מראש ועם המכונה להוסיף עוד. חוויה מדהימה, הילדים נהנו המבוגרים נהנו. הכל במקצועיות ורוחב לב, ממליצים בחום", photo: "", screenshot: "" },
    { name: "עינב צברי",           text: "הזמנו את הושעיה לעצב את הבת-מצווה. במקצועיות ומיומנות מדהימה המועדון הפך לאולם אירועים יפהפה. חילק כתרים מבלונים מעוצבים, שידרג את האירוע ברמות. ממליצה בחום!", photo: "", screenshot: "" },
    { name: "שירה כהן",            text: "תודה רבה! נהנינו מאוד! גם הקטנים וגם הגדולים!", photo: "", screenshot: "" },
    { name: "עידן יוסף וניצן ליבן", text: "תודה רבה על ערב בלתי נשכח, הבלונים שדרגו אותו מאוד בצבעם ובייחודם. כשרון מהמם וכולם מהקטנטנים ועד הגדולים נהנו מאוד", photo: "", screenshot: "" },
    { name: "משפחת ארביט",         text: "הבלונים שעשית היו מקסימים, כל הכבוד אתה מקצוען", photo: "", screenshot: "" },
    { name: "יגל ויסכה שרעבי",     text: "הושעיה המוכשר עשה לנו פשוט שמח בבר מצווה! מלא סבלנות, עשה מלא כובעים ודמויות לפי בקשות. ממליצים בחום!", photo: "", screenshot: "" },
    { name: "איתן ויפעת חובב",     text: "ממליצה בחום! שידרג לנו את הבר מצווה. הכל היה מוכן בזמן. מענה מהיר וזמינות. מחכים כבר לאירוע הבא!", photo: "", screenshot: "" }
  ]
};
